# Generated by Django 2.2.7 on 2020-01-24 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('knox', '0007_auto_20190111_0542'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BasicWeatherData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(default=0)),
                ('pressure', models.FloatField(default=0)),
                ('pressureSea', models.FloatField(default=0, null=True, verbose_name='sea level pressure')),
                ('pressureGround', models.FloatField(default=0, null=True, verbose_name='ground pressure')),
                ('humidity', models.IntegerField(default=0)),
                ('tempMin', models.FloatField(default=0, verbose_name='min temp')),
                ('tempMax', models.FloatField(default=0, verbose_name='max temp')),
                ('clouds', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='DayInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sunrise', models.DateTimeField(default=django.utils.timezone.now)),
                ('sunset', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('flightID', models.AutoField(primary_key=True, serialize=False)),
                ('dateOfFlight', models.DateTimeField(verbose_name='date of flight')),
                ('dateRecorded', models.DateTimeField(verbose_name='date recorded')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('size', models.IntegerField(choices=[(0, 'One queen'), (1, 'many ants')], default=1, verbose_name='size of flight')),
                ('confidence', models.IntegerField(blank=True, choices=[(0, 'Low'), (1, 'Medium'), (2, 'Hight')], null=True, verbose_name='Species confidence level')),
                ('image', models.ImageField(blank=True, null=True, upload_to='flight_pics')),
            ],
        ),
        migrations.CreateModel(
            name='RainInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rain1', models.FloatField(default=0, null=True, verbose_name='rain 1 hour')),
                ('rain3', models.FloatField(default=0, null=True, verbose_name='rain 3 hour')),
            ],
        ),
        migrations.CreateModel(
            name='WeatherDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desc', models.CharField(blank=True, default='', max_length=64, verbose_name='description')),
                ('longDesc', models.CharField(blank=True, default='', max_length=128, verbose_name='full description')),
            ],
        ),
        migrations.CreateModel(
            name='WindInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('windSpeed', models.FloatField(default=0, null=True, verbose_name='speed')),
                ('windDegree', models.IntegerField(default=0, null=True, verbose_name='direction')),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('deviceID', models.BigIntegerField(default=0, primary_key=True, serialize=False, verbose_name='Device ID')),
                ('platform', models.CharField(choices=[('IOS', 'iOS'), ('ANDROID', 'Android')], max_length=10)),
                ('model', models.CharField(max_length=64)),
                ('deviceToken', models.CharField(blank=True, max_length=65, null=True)),
                ('lastLoggedIn', models.DateTimeField(verbose_name='last logged in')),
                ('active', models.BooleanField(default=True)),
                ('authToken', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='knox.AuthToken')),
                ('user', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='devices', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
