# Generated by Django 2.2.7 on 2020-01-24 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nuptiallog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='flight',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='flights', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeFetched', models.DateTimeField(default=django.utils.timezone.now)),
                ('day', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='nuptiallog.DayInfo')),
                ('description', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='nuptiallog.WeatherDescription')),
                ('flight', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nuptiallog.Flight')),
                ('rain', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nuptiallog.RainInfo')),
                ('weather', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='nuptiallog.BasicWeatherData')),
                ('wind', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='nuptiallog.WindInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('genus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='species', to='nuptiallog.Genus')),
            ],
        ),
        migrations.CreateModel(
            name='FlightUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='nuptiallog.Role')),
                ('species', models.ManyToManyField(blank=True, to='nuptiallog.Species')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('time', models.DateTimeField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('responseTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='nuptiallog.Flight')),
            ],
        ),
        migrations.CreateModel(
            name='Changelog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.TextField()),
                ('date', models.DateTimeField()),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='changes', to='nuptiallog.Flight')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='changes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='flight',
            name='genus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='nuptiallog.Genus'),
        ),
        migrations.AddField(
            model_name='flight',
            name='species',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='nuptiallog.Species'),
        ),
    ]
