# Generated by Django 2.2.7 on 2020-05-27 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuptiallog', '0004_auto_20200515_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightuser',
            name='genera',
            field=models.ManyToManyField(blank=True, to='nuptiallog.Genus'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='confidence',
            field=models.IntegerField(blank=True, choices=[(0, 'Low'), (1, 'High')], null=True, verbose_name='Species confidence level'),
        ),
        migrations.AlterField(
            model_name='flight',
            name='size',
            field=models.IntegerField(choices=[(0, 'Many queens'), (1, 'One queen')], default=1, verbose_name='size of flight'),
        ),
    ]
