# Generated by Django 2.2 on 2020-06-02 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuptiallog', '0005_auto_20200527_0141'),
    ]

    operations = [
        migrations.AddField(
            model_name='flightuser',
            name='flagged',
            field=models.BooleanField(default=False),
        ),
    ]
