# Generated by Django 2.2 on 2020-06-05 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nuptiallog', '0006_flightuser_flagged'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='validatedAt',
            field=models.DateTimeField(blank=True, null=True, verbose_name='date of validation'),
        ),
        migrations.AddField(
            model_name='flight',
            name='validatedBy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validatedFlights', to='nuptiallog.FlightUser'),
        ),
    ]
