# Generated by Django 2.2 on 2020-07-03 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuptiallog', '0007_auto_20200605_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basicweatherdata',
            name='tempMax',
            field=models.FloatField(default=0, null=True, verbose_name='max temp'),
        ),
        migrations.AlterField(
            model_name='basicweatherdata',
            name='tempMin',
            field=models.FloatField(default=0, null=True, verbose_name='min temp'),
        ),
    ]
