# Generated by Django 2.2.13 on 2020-07-29 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuptiallog', '0008_auto_20200703_1808'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScientificAdvisor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
                ('position', models.CharField(max_length=125)),
                ('image', models.ImageField(upload_to='')),
                ('url', models.URLField()),
            ],
        ),
    ]
