# Generated by Django 2.2.13 on 2020-07-29 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuptiallog', '0009_scientificadvisor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scientificadvisor',
            name='image',
            field=models.ImageField(upload_to='scientist_pics'),
        ),
        migrations.AlterField(
            model_name='scientificadvisor',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
