# Generated by Django 3.2.3 on 2021-06-16 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuptiallog', '0010_auto_20200729_1519'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='platform',
            field=models.CharField(choices=[('IOS', 'iOS'), ('ANDROID', 'Android'), ('WINDOWS', 'Windows'), ('MACOS', 'macOS'), ('LINUX', 'Linux'), ('FUCHSIA', 'Fuchsia')], max_length=10),
        ),
    ]
