# Generated by Django 3.2.3 on 2021-08-02 18:47

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nuptiallog', '0013_flightimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='flight',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, default=None, srid=4326),
        ),
    ]
