# Generated by Django 3.2.3 on 2021-08-02 19:08

from django.db import migrations
from django.contrib.gis.geos import Point

def change_images(apps, schema_editor):
    Flight = apps.get_model('nuptiallog', 'Flight')
    FlightImage = apps.get_model('nuptiallog', 'FlightImage')

    flights = Flight.objects.exclude(image='')
   
    for flight in flights:
        image = flight.image
        flight_image = FlightImage(image=image, flight=flight, created_by=flight.owner, date_created=flight.dateRecorded)
        flight_image.save()



def set_locations(apps, schema_editor):
    Flight = apps.get_model('nuptiallog', 'Flight')

    for flight in Flight.objects.all():
        lat = flight.latitude
        lon = flight.longitude
        point = Point(lon, lat)
        flight.location = point
        flight.save()


class Migration(migrations.Migration):

    dependencies = [
        ('nuptiallog', '0014_flight_location'),
    ]

    operations = [
        migrations.RunPython(change_images),
        migrations.RunPython(set_locations),
    ]
