# Generated by Django 3.2.3 on 2021-08-17 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuptiallog', '0015_auto_20210802_1908'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='deviceToken',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
