# Generated by Django 3.2.3 on 2021-08-17 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuptiallog', '0016_alter_device_devicetoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='deviceToken',
            field=models.TextField(blank=True, default=''),
        ),
    ]
