# Generated by Django 3.2.3 on 2021-08-17 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuptiallog', '0017_alter_device_devicetoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='deviceToken',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
