# Generated by Django 3.2.3 on 2021-12-21 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nuptiallog', '0018_alter_device_devicetoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='Taxonomy',
            fields=[
                ('version', models.BigAutoField(primary_key=True, serialize=False)),
                ('updated', models.DateTimeField()),
                ('genera', models.ManyToManyField(to='nuptiallog.Genus')),
                ('species', models.ManyToManyField(to='nuptiallog.Species')),
            ],
        ),
    ]
