# Generated by Django 3.2.20 on 2024-09-20 20:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nuptiallog', '0019_taxonomy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='changelog',
            name='flight',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to='nuptiallog.flight'),
        ),
        migrations.AlterField(
            model_name='changelog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='changes', to=settings.AUTH_USER_MODEL),
        ),
    ]
